# Generated by Django 3.2.6 on 2021-08-27 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='readerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followings', models.IntegerField(default=0)),
                ('isValidated', models.BooleanField(default=False)),
                ('User_Name', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('followingList', models.ManyToManyField(related_name='followerList', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
