# Generated by Django 3.2.6 on 2021-08-27 04:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readerdetails',
            name='followingList',
            field=models.ManyToManyField(related_name='followingList', to=settings.AUTH_USER_MODEL),
        ),
    ]
