# Generated by Django 3.2.6 on 2021-08-27 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_readerdetails_followinglist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readerdetails',
            name='isValidated',
        ),
    ]
