# Generated by Django 3.2.6 on 2021-08-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writerdetails',
            name='followerList',
            field=models.ManyToManyField(blank=True, related_name='_writer_writerdetails_followerList_+', to='writer.writerDetails'),
        ),
    ]
