# Generated by Django 3.2.6 on 2021-08-27 04:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writer', '0003_alter_writerdetails_followerlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writerdetails',
            name='followerList',
            field=models.ManyToManyField(related_name='followerList', to=settings.AUTH_USER_MODEL),
        ),
    ]
