# Generated by Django 3.2.6 on 2021-08-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0004_alter_writerdetails_followerlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='writerdetails',
            name='User_Name_Trial',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
