# Generated by Django 3.2.6 on 2021-08-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_post_users_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='followers',
            field=models.IntegerField(default=0),
        ),
    ]
