# Generated by Django 3.2.6 on 2021-08-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isValidated',
            field=models.BooleanField(default=False),
        ),
    ]
